version: "2.4"
    
services:
    webhost: 
        image: docker/frontend
        container_name: webhost
        ports: 
            - 80:80
        networks: 
            - front
            - back

    api: 
        image: docker/backend
        container_name: api
        ports: 
            - 8000:8000
        networks: 
            - front
            - back    

networks: 
    front:
        driver: bridge
    back:
        driver: bridge
